### PR TITLE
add dave to maintainer

### PR DESCRIPTION
**Pull request by gwaybio**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding @d33bs as maintainer, related to #9

### CODE REVIEW

**Comment by gwaybio** [comment]
@conda-forge-admin, please rerender

**Comment by gwaybio** [comment]
@conda-forge-admin, please rerender

**Comment by gwaybio** [comment]
@d33bs - does this look good to you to merge? I'm happy to merge (as long as you are), and then address any necessary fixes in #9

**Comment by d33bs** [comment]
Thanks @gwaybio ! Yes, this LGTM!

Being explicit here to make sure: I understood the remaining comment from conda-forge-admin `No valid build backend found for Python recipe ...` to mean it had trouble detecting that we're using `poetry`.

**Comment by gwaybio** [comment]
yep, i agree. Ok, i'll merge in and we can solve #9 🤞

**Pull request merged**
