### PR TITLE
Pycytominer v1.2.0

### PR DESCRIPTION
**Pull request by d33bs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Opening after a premature close on #9 .

### CODE REVIEW

**Comment by d33bs** [comment]
After setting Python constraints to address the original errors I'm finding there's an additional error from `pip check`:  `backports.tempfile 1.0 is not supported on this platform`. `backports.tempfile` is a dependency of Pycytominer via `cytominer-database`. I believe the error may be stemming from the build platform (OS and architecture), Python version (3.10.15), and possibly other constraints. The last successful build used Python 3.10.13 ([see here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=895781&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3)).

**Comment by hmaarrfk** [comment]
Just remove it as a dependecy from https://github.com/conda-forge/cytominer_database-feedstock/blob/main/recipe/meta.yaml

Python 3.4 is way out of date, but even that should support TemporaryDirectory natively.

https://pypi.org/project/backports.tempfile/

**Comment by hmaarrfk** [comment]
There are other hacks you can do, but generally they aren't worth it for Python 3.3. compatibility.

This seemed easy: https://github.com/conda-forge/dataclasses-feedstock/pull/3
Then the churn: https://github.com/conda-forge/dataclasses-feedstock/pull/9
continues: https://github.com/conda-forge/dataclasses-feedstock/pull/14

**Review by gwaybio — APPROVED** [review]

**Comment by d33bs** [comment]
Thanks @gwaybio for the review! Also, thank you @hmaarrfk for the continued guidance throughout this PR and the other related ones along the journey, we really appreciate it! Merging this in now.

**Pull request merged**
